INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Charmander', 'Lizard Pokémon', 'Scratch', '10', 'Water', NULL, '1 Colorless', 46, 1, 1, 1),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '10', 'Electric', NULL, '1 Colorless', 7, 1, 2, 1),
(40, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', 'Metal', '1 Colorless', 58, 1, 4, 1),
(90, 'Ivysaur', 'Seed Pokémon', 'Vine Whip', '30', 'Fire', NULL, '2 Colorless', 30, 1, 3, 2),
(120, 'Charizard', 'Flame Pokémon', 'Fire Spin', '100', 'Water', NULL, '3 Colorless', 4, 1, 1, 3),
(70, 'Bulbasaur', 'Seed Pokémon', 'Leech Seed', '20', 'Fire', NULL, '1 Colorless', 44, 1, 3, 1),
(80, 'Wartortle', 'Turtle Pokémon', 'Water Gun', '40', 'Electric', NULL, '1 Colorless', 42, 1, 2, 2),
(100, 'Blastoise', 'Shellfish Pokémon', 'Hydro Pump', '60', 'Electric', NULL, '3 Colorless', 2, 1, 2, 3),
(60, 'Jigglypuff', 'Balloon Pokémon', 'Pound', '20', 'Fighting', NULL, '1 Colorless', 54, 1, 10, 1),
(70, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', NULL, '1 Colorless', 56, 1, 10, 1),
(80, 'Persian', 'Classy Cat Pokémon', 'Slash', '30', 'Fighting', NULL, '2 Colorless', 36, 1, 10, 2),
(60, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', NULL, '1 Colorless', 52, 1, 6, 1),
(90, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', NULL, '2 Colorless', 34, 1, 6, 2),
(120, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', NULL, '3 Colorless', 8, 1, 6, 3),
(50, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', NULL, '1 Colorless', 33, 1, 5, 1),
(80, 'Haunter', 'Gas Pokémon', 'Nightmare', '30', 'Psychic', NULL, '2 Colorless', 29, 1, 5, 2),
(100, 'Gengar', 'Shadow Pokémon', 'Dark Mind', '60', 'Psychic', NULL, '3 Colorless', 5, 1, 5, 3),
(70, 'Eevee', 'Evolution Pokémon', 'Quick Attack', '20+', 'Fighting', NULL, '1 Colorless', 55, 1, 10, 1),
(90, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Electric', NULL, '2 Colorless', 28, 2, 2, 2),
(100, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', NULL, '2 Colorless', 27, 2, 4, 2);
