INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', NULL, '1 Colorless', 58, 2, 3, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', NULL, '2 Colorless', 32, 2, 3, 2),
(100, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', NULL, '2 Colorless', 15, 2, 3, 3),
(50, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Electric', NULL, '1 Colorless', 60, 1, 2, 1),
(80, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '20', 'Electric', NULL, '2 Colorless', 36, 1, 2, 2),
(100, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Electric', NULL, '3 Colorless', 13, 1, 2, 3),
(40, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', NULL, '1 Colorless', 43, 1, 5, 1),
(60, 'Kadabra', 'Psi Pokémon', 'Recover', NULL, 'Psychic', NULL, '2 Colorless', 32, 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', NULL, '3 Colorless', 1, 1, 5, 3),
(50, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', NULL, '1 Colorless', 47, 1, 6, 1),
(70, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', NULL, '2 Colorless', 19, 1, 6, 2),
(60, 'Geodude', 'Rock Pokémon', 'Tackle', '10', 'Grass', NULL, '1 Colorless', 45, 1, 6, 1),
(80, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', NULL, '2 Colorless', 37, 1, 6, 2),
(100, 'Golem', 'Megaton Pokémon', 'Selfdestruct', '100', 'Grass', NULL, '3 Colorless', 26, 1, 6, 3),
(50, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'Metal', '1 Colorless', 62, 1, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Thunder Wave', '30', 'Fighting', 'Metal', '2 Colorless', 9, 1, 4, 2),
(60, 'Voltorb', 'Ball Pokémon', 'Tackle', '10', 'Fighting', NULL, '1 Colorless', 67, 1, 4, 1),
(80, 'Electrode', 'Ball Pokémon', 'Tackle', '20', 'Fighting', NULL, '2 Colorless', 21, 1, 4, 2),
(50, 'Koffing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', NULL, '1 Colorless', 60, 1, 6, 1),
(80, 'Weezing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', NULL, '2 Colorless', 44, 1, 6, 2),
(70, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', NULL, '1 Colorless', 56, 1, 10, 1),
(80, 'Raticate', 'Mouse Pokémon', 'Super Fang', NULL, 'Fighting', NULL, '2 Colorless', 40, 1, 10, 2),
(60, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Psychic', NULL, '1 Colorless', 57, 2, 3, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', NULL, '2 Colorless', 33, 2, 3, 2),
(100, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '30', 'Fighting', NULL, '4 Colorless', 11, 2, 10, 1),
(60, 'Cubone', 'Lonely Pokémon', 'Bone Attack', '20', 'Grass', NULL, '1 Colorless', 50, 2, 6, 1),
(90, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '30x', 'Grass', NULL, '2 Colorless', 39, 2, 6, 2),
(70, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', NULL, '1 Colorless', 10, 2, 3, 1),
(80, 'Pinsir', 'Stag Beetle Pokémon', 'Guillotine', '50', 'Fire', NULL, '2 Colorless', 6, 2, 3, 1),
(100, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '20x', 'Fighting', NULL, '3 Colorless', 5, 2, 10, 1);
