INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Ekans', 'Snake Pokémon', 'Wrap', '10', 'Psychic', NULL, '1 Colorless', 69, 1, 6, 1),
(80, 'Arbok', 'Cobra Pokémon', 'Poison Fang', '20', 'Psychic', NULL, '2 Colorless', 31, 1, 6, 2),
(50, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '10', 'Water', NULL, '1 Colorless', 67, 1, 6, 1),
(80, 'Sandslash', 'Mouse Pokémon', 'Slash', '30', 'Water', NULL, '2 Colorless', 22, 1, 6, 2),
(60, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', NULL, '1 Colorless', 63, 1, 3, 1),
(70, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', NULL, '2 Colorless', 36, 1, 3, 2),
(100, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', NULL, '3 Colorless', 7, 1, 3, 3),
(60, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Attack', '20', 'Psychic', NULL, '1 Colorless', 64, 1, 6, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', NULL, '2 Colorless', 39, 1, 6, 2),
(120, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', NULL, '3 Colorless', 11, 1, 6, 3),
(50, 'Clefairy', 'Fairy Pokémon', 'Sing', NULL, 'Fighting', NULL, '1 Colorless', 5, 1, 10, 1),
(90, 'Clefable', 'Fairy Pokémon', 'Metronome', NULL, 'Fighting', NULL, '2 Colorless', 6, 1, 10, 2),
(60, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '10', 'Electric', NULL, '1 Colorless', 57, 1, 10, 1),
(80, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Electric', NULL, '2 Colorless', 22, 1, 10, 2),
(120, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '30', 'Electric', NULL, '2 Colorless', 8, 1, 10, 3),
(50, 'Spearow', 'Tiny Bird Pokémon', 'Peck', '10', 'Electric', NULL, '1 Colorless', 63, 2, 10, 1),
(80, 'Fearow', 'Beak Pokémon', 'Agility', '20', 'Electric', NULL, '2 Colorless', 36, 2, 10, 2),
(100, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Electric', NULL, '2 Colorless', 19, 2, 10, 2),
(60, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', NULL, '1 Colorless', 60, 2, 3, 1),
(80, 'Parasect', 'Mushroom Pokémon', 'Stun Spore', '30', 'Fire', NULL, '2 Colorless', 34, 2, 3, 2),
(70, 'Venonat', 'Insect Pokémon', 'Stun Spore', '10', 'Fire', NULL, '1 Colorless', 63, 2, 3, 1),
(90, 'Venomoth', 'Poison Moth Pokémon', 'Venom Powder', '10', 'Fire', NULL, '1 Colorless', 13, 2, 3, 2),
(60, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '10', 'Electric', NULL, '1 Colorless', 51, 3, 2, 1),
(80, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '40', 'Electric', NULL, '2 Colorless', 34, 3, 2, 2),
(70, 'Omanyte', 'Spiral Pokémon', 'Water Gun', '10+', 'Grass', NULL, '1 Colorless', 52, 3, 2, 1),
(90, 'Omastar', 'Spiral Pokémon', 'Hydro Pump', '30+', 'Grass', NULL, '2 Colorless', 26, 3, 2, 2),
(60, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '10', 'Grass', NULL, '1 Colorless', 50, 3, 6, 1),
(80, 'Kabutops', 'Shellfish Pokémon', 'Slash', '30', 'Grass', NULL, '2 Colorless', 24, 3, 6, 2),
(70, 'Aerodactyl', 'Fossil Pokémon', 'Wing Attack', '30', 'Electric', NULL, '2 Colorless', 1, 3, 6, 1),
(100, 'Lapras', 'Transport Pokémon', 'Water Gun', '10+', 'Electric', NULL, '2 Colorless', 10, 3, 2, 1);
